# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Embember
tagline:             'Stories from Embedded Plumber'
description:         'Personal blog of Jari Tulilahti'
url:                 https://jartza.github.io
baseurl:             ''
paginate:            25

# About/contact
author:
  name:              Jari Tulilahti
#  url:               https://twitter.com/mdo
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
